# Generated by Django 3.2.5 on 2021-07-20 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='툴 이름', max_length=50)),
                ('kind', models.CharField(help_text='툴 종류', max_length=50)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='아이디어 이름', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea_img/%Y/%m/%d')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0, help_text='interest')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('devtool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.tool')),
            ],
        ),
    ]
